# Generated by Django 4.2.16 on 2024-10-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enqueteur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='localisation',
        ),
    ]
